### Read all users
GET http://localhost:3002/users

### Create a new user
POST http://localhost:3002/users
Content-Type: application/json

{
    "username": "Charlie", 
    "email": "charlie@example.com",
    "password": "pass123"
}

### Update a user
PUT http://localhost:3002/users/1
Content-Type: application/json

{
    "username": "Neeti2", 
    "email": "neeti@example.com",
    "password": "pass123"
}