### Read all users
GET http://localhost:3002/api/v1/users

### Create a new user
POST http://localhost:3002/api/v1/users
Content-Type: application/json

{
    "username": "Charlie", 
    "email": "charlie@example.com",
    "password": "pass123"
}

### Update a user
PUT http://localhost:3002/api/v1/users/1
Content-Type: application/json

{
    "username": "Neeti3", 
    "email": "neeti@example.com",
    "password": "pass123"
}

### DELETE a user
DELETE http://localhost:3002/api/v1/users/1